# mysql 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ${MYSQL_USER:root}
      password: ${PASS_COMMON_2:123456}
      url: jdbc:mysql://${MYSQL_HOST:allbs-mysql}:${MYSQL_PORT:3306}/${MYSQL_DB:authorization_demo}?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&allowMultiQueries=true&allowPublicKeyRetrieval=true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
          enabled: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    database: 2
    host: ${REDIS_HOST_DEV:127.0.0.1}
    port: 6379
    password: ${REDIS_PWD_DEV:123456}
    timeout: 5000
    lettuce:
      pool:
        min-idle: 2
# mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.allbs.allbsjwt.config.handler
  show-sql: true
  meta-custom:
    del-flg: delFlag
    create-name: createId
    update-name: updateId
  chine-rate: 1.5
  data-pms: true

# swagger3
swagger:
  title: jwt示例
  description: jwt示例服务
  version: 1.0
  securitySchemes:
    Authorization:
      type: http  #类型
      in: HEADER    #放 header 里面
      name: Authorization # header - key
      scheme: bearer

  servers:
    - url: http://127.0.0.1:8888 #服务器 URL
      description: 本地服务器
springdoc:
  api-docs:
    # 开启api-docs
    enabled: true
  # 配置需要生成接口文档的扫描包
  packages-to-scan: cn.allbs.allbsjwt.controller
  # 配置需要生成接口文档的接口路径
  paths-to-match:
security:
  ignore-urls:
    - /v3/api-docs/**
    - /doc.html
    - /webjars/**
    - /druid/**
    - /static/**
    - /configuration/ui
    - /swagger-resources/**
